use_default_settings: true

general:
  instance_name: "Claygent Search"
  debug: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

server:
  secret_key: "0742863fd735c000f8e99a726295cd0fae517db834b15d987aa9c341b1221ca1"
  limiter: false
  public_instance: false
  image_proxy: false
  bind_address: "0.0.0.0"
  port: 8080

outgoing:
  request_timeout: 10
  useragent_suffix: ""
  proxies:
    all://:
    - http://lenvthja-1:0knwfjsefp8v@p.webshare.io:80
    - http://lenvthja-2:0knwfjsefp8v@p.webshare.io:80
    - http://lenvthja-3:0knwfjsefp8v@p.webshare.io:80
    - http://lenvthja-4:0knwfjsefp8v@p.webshare.io:80
    - http://lenvthja-5:0knwfjsefp8v@p.webshare.io:80

engines:
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
    weight: 1.5

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
    weight: 1.5

  - name: brave
    engine: brave
    shortcut: br
    disabled: false
    weight: 1.5

  - name: google
    engine: google
    shortcut: g
    disabled: false
    weight: 0.5

  - name: google images
    disabled: true
  - name: bing images
    disabled: true
  - name: google videos
    disabled: true
  - name: bing videos
    disabled: true
  - name: youtube
    disabled: true
  - name: dailymotion
    disabled: true
  - name: vimeo
    disabled: true
  - name: soundcloud
    disabled: true
  - name: bandcamp
    disabled: true
